### ISSUE TITLE
Allergies and Intolerances Section Examples from C-CDA

### ISSUE THREAD

**Issue by brettmarquard** [HL7/hl7-c-cda-ex#32]
The text 'XXXX Section Examples from C-CDA' seems redundant on main page.

Could we just display the folder title?

http://hl7-c-cda-examples.herokuapp.com/

**Comment by astechishin** [comment]
I agree that the text is almost always redundant. However, I believe this is a content issue rather than something we should 'fix' by removing current functionality. If the Readme.md files for each section (and in the future documents) are updated, this will update the description of the section/document. Then as you update the section readme files in the future, you will not need to pay someone to add back a feature that existed originally and was deleted.

The section/document directory level readme files are also the only way to tell if the directory contains section or document examples. The metadata parser looks fro the text 'Section Example' and if it finds it, marks the directory as a Section else it marks the directory as a Document. We may wish to formalize how these are designated.

**Comment by brettmarquard** [comment]
Is there a way to tell the parser to 'stop'?

See medications.

The text is for folks reviewing samples and shouldn't display on search page:

"For all Medication examples the example task force agreed (8/28/2014) to only include institutionSpecified on the effectiveTime when the value is true. InstitutionSpecified indicates whether the exact timing is up to the party executing the schedule (e.g., to distinguish "every 8 hours" (false) from "3 times a day" (true))."

**Comment by astechishin** [comment]
I think the problem here is we are trying to make one thing support two very different purposes. You need a mechanism to communicate with example authors in the Git repository and the example search needs a way to have data about the section/document directory communicated.

I would recommend the best is to use the Readme.md for communication example authors. The metadata parser would ignore this file in the Section and Document directories. The Readme.md file in the example directories would continue to be the source of metadata for each example. We would create a new file called Description.md in the Section and Document directories to contain any descriptive text you wish to display on the section/document and to define the directory as containing section or document examples.

**Comment by brettmarquard** [comment]
Could we have a default?

**Comment by astechishin** [comment]
Not sure I understand, a default for what exactly?

**Comment by brettmarquard** [comment]
did you already build the description.md functionality?

**Comment by astechishin** [comment]
No, I just made a recommendation. If you agree that this is the way to go then I can see about adding it.

**Comment by brettmarquard** [comment]
for default, I was thinking just a generic <folder name> + <Section|Document> examples

**Comment by astechishin** [comment]
Still not clear on what the default would apply to.

**Comment by brettmarquard** [comment]
Allergies and Intolerances Section Examples from C-CDA
Encounter Section Examples from C-CDA
Family History Section Examples from C-CDA
General Section Examples from C-CDA
Immunization Section Examples from C-CDA
....
Seems like it would be great to have section readme.md do both -- provide title, and brief description

**Comment by astechishin** [comment]
It can do that now, add as much as you would like. Part of the issue was that you added text to the readme.md file that you did not want to display in the tool.

But you can right now add whatever text formatted in Markdown for the section and it will display

**Comment by brettmarquard** [comment]
...sure...but I don't want description to display :)

Multiples seems awkward, can we have a heading called 'title' that you pull into main search page?

**Comment by dhamill** [comment]
Adding a summary of emails that went back and forth between Andy, Brett and Dave.
Need to determine next steps for this issue.


To summarize the requirements:

1. There needs to be a mechanism to describe each section.
2. The Readme files in each section need to convey information to the sample authors (when using the GitHub web interface, the Readme file appears as the description).
3. There are additional attributes such as section type (section, document, header) and short description that will be needed over time.

Andy proposes 3 options:

I) Status Quo - continue to use the Readme file
 
Pros:
 - no extra work (no cost)
Cons:
 - descriptions are inaccurate
 - mixed use causes issues for both search tool and GitHub
 
 
II) Create new description.md file containing information for search tool
 
Pros:
 - minimal code change (no cost)
 - contains only information to display in search tool
 - allows readme file to be specific to content authors and GitHub display
Cons:
 - authors must maintain two files for each section
 
Comments/Questions:
Q: What would happen if a description.md file didn’t exist in a directory?
A:The section/document would have no description, only the name (which is currently what happens if there is no Readme file in the section directory).


Q:What will go in Readme vs description.md?
A: The Readme would contain what you wanted people to see when they navigate to the section directory in GitHub, pretty much the same as what you have now. The description.md  would have text that you want to display in the search tool. Perhaps a description of the purpose of the section, notes on the types of examples and so forth. But not a repeat of the title or directions for the example content authors.
 
III) Create metadata format for sections
 
Pros:
 - tailored to actual needs
 - define specific metadata needed for the sections (section type, short description, long description)
 - only 1 file needs to be maintained
 - extra text that displays in GitHub can be ignored by parser
Cons:
 - database reload required (cost) (Andy provided Dave with the estimate)
 - requires significant code changes (cost) (Andy provided Dave with the estimate)
 - updates to every section Readme

Comments: The cost of option III is variable based on whether to maintain the example IDs. Without maintaining the IDs the effort is 2.5 days. With maintaining the IDs, the effort is 5 days.

**Comment by brettmarquard** [comment]
can we just read the first line of readme for the search screen?
